# Set language
language: php

# Set php versions we can work with
php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm

# Thing to install before the actual building process
install:
 - composer self-update # This should not be required, but it is always a good practice to update composer
 - composer install
 - composer require satooshi/php-coveralls:~1.0@stable # Require phpCoveralls

# Run before the build
before_script:
 - mkdir -p build/logs # Create a folder to store clover files

# Set list of allowed build failures
matrix:
  allow_failures:
    - php: 5.4 # Too Old
    - php: 7.0 # Too New
    - php: hhvm # Too unstable

# Build Script. Notice: We are demanding unit to generate a clover file to our previously created folder
script: 
  # Syntax: phpunit --coverage-clover <folder>/<name>.xml --text-suffix .php [--colors] [--report-useless-tests] <tests location>.php
 - phpunit --coverage-clover build/logs/clover.xml --test-suffix .php --colors --report-useless-tests tests/test.php

# After success, run sh to bind coveralls
after_success:
 - sh -c 'if( [ "$TRAVIS_PHP_VERSION" != "hhvm" ] ); then php vendor/bin/coveralls -v; fi;'
